Repository vskurikhin/daybook, pull requests merged in 2020-02, with the labels that each got.

#7 Added liquibase activity db_dictionary.
  build.gradle
  src/main/db/dictionary/Change-Sets/changelogs-2020-02-01-dictionary-110.codifier.postgresql.sql
  src/main/db/dictionary/Change-Sets/changelogs-2020-02-01-dictionary-115.words.postgresql.sql
  src/main/db/dictionary/Change-Sets/changelogs-2020-02-01-dictionary-120.vocabulary.postgresql.sql
  src/main/db/dictionary/Change-Sets/changelogs-2020-02-01-dictionary-130.tag.postgresql.sql
  src/main/db/dictionary/Change_Log.xml
  src/main/db/public/Change-Sets/changelogs-2020-02-01_21-30-00-public.schemas.postgresql.sql
Labels: enhancement

#10 Liquibase 02
  build.gradle
  src/main/db/db/Change-Sets/changelogs-2020-02-02-db-200.db_user_login.postgresql.sql
  src/main/db/db/Change-Sets/changelogs-2020-02-02-db-210.db_role.postgresql.sql
  src/main/db/db/Change-Sets/changelogs-2020-02-02-db-220.db_user_role.postgresql.sql
  src/main/db/db/Change_Log.xml
Labels: bug

#11 Added relations db_news_entry, db_news_group, db_record and db_record…
  src/main/db/db/Change-Sets/changelogs-2020-02-02-db-230.db_news_group.postgresql.sql
  src/main/db/db/Change-Sets/changelogs-2020-02-02-db-235.db_record.postgresql.sql
  src/main/db/db/Change-Sets/changelogs-2020-02-02-db-240.db_news_entry.postgresql.sql
  src/main/db/db/Change-Sets/changelogs-2020-02-02-db-250.db_record_tag.postgresql.sql
Labels: enhancement

#14 Added docker-compose infrestructure support,
  gradlew
  gradlew.bat
  src/test/docker/docker-compose.yml
  src/test/docker/postgresql/Dockerfile
  src/test/docker/sql/01-changelogs.postgresql.sql
  src/test/docker/sql/10-changelogs-dictionary-20191024_224651.postgresql.sql
  src/test/docker/sql/20-changelogs-db-20191024_224651.postgresql.sql
Labels: enhancement

#16 This close vskurikhin/daybook #15
  Dockerfile
Labels: bug

#17 Build
  Dockerfile
  build.gradle
  gradle.properties
  gradlew
  gradlew.bat
  src/main/db/db/Change-Sets/changelogs-2020-02-02-db-200.db_user_login.postgresql.sql
  src/main/db/db/Change-Sets/changelogs-2020-02-02-db-210.db_role.postgresql.sql
  src/main/db/db/Change-Sets/changelogs-2020-02-02-db-220.db_user_role.postgresql.sql
  src/main/db/db/Change-Sets/changelogs-2020-02-02-db-230.db_news_group.postgresql.sql
  src/main/db/db/Change-Sets/changelogs-2020-02-02-db-235.db_record.postgresql.sql
  src/main/db/db/Change-Sets/changelogs-2020-02-02-db-240.db_news_entry.postgresql.sql
  src/main/db/db/Change-Sets/changelogs-2020-02-02-db-250.db_record_tag.postgresql.sql
  src/main/db/db/Change_Log.xml
  src/main/db/dictionary/Change-Sets/changelogs-2020-02-01-dictionary-110.codifier.postgresql.sql
  src/main/db/dictionary/Change-Sets/changelogs-2020-02-01-dictionary-115.words.postgresql.sql
  src/main/db/dictionary/Change-Sets/changelogs-2020-02-01-dictionary-120.vocabulary.postgresql.sql
  src/main/db/dictionary/Change-Sets/changelogs-2020-02-01-dictionary-130.tag.postgresql.sql
  src/main/db/dictionary/Change_Log.xml
  src/main/db/drop.sql
  src/main/db/public/Change-Sets/changelogs-2020-01-31_14-10-00-public.search_path.postgresql.sql
  src/main/db/public/Change-Sets/changelogs-2020-01-31_14-10-00-public.uuid.postgresql.sql
  src/main/db/public/Change-Sets/changelogs-2020-01-31_14-20-00-public.dual.postgresql.sql
  src/main/db/public/Change-Sets/changelogs-2020-02-01_21-30-00-public.schemas.postgresql.sql
  src/main/db/public/Change_Log.xml
  src/test/docker/docker-compose.yml
  src/test/docker/postgresql/Dockerfile
  src/test/docker/sql/01-changelogs.postgresql.sql
  src/test/docker/sql/10-changelogs-dictionary-20191024_224651.postgresql.sql
  src/test/docker/sql/20-changelogs-db-20191024_224651.postgresql.sql
Labels: enhancement

#18 Devops 01
  Jenkinsfile
  README.md
  build.gradle
  src/test/docker/sql/10-changelogs-dictionary-20191024_224651.postgresql.sql
  src/test/docker/sql/20-changelogs-db-20191024_224651.postgresql.sql
Labels: enhancement

#19 Build
  Jenkinsfile
  README.md
  build.gradle
  src/test/docker/sql/10-changelogs-dictionary-20191024_224651.postgresql.sql
  src/test/docker/sql/20-changelogs-db-20191024_224651.postgresql.sql
Labels: enhancement

#21 Model
  .github/workflows/gradle.yml
  src/main/java/su/svn/showcase/domain/DBEntity.java
  src/main/java/su/svn/showcase/domain/LongEntity.java
  src/main/java/su/svn/showcase/domain/StringEntity.java
  src/main/java/su/svn/showcase/domain/UUIDEntity.java
  src/main/java/su/svn/showcase/utils/BigIntegerUtil.java
  src/main/java/su/svn/showcase/utils/LongUtil.java
  src/main/java/su/svn/showcase/utils/StringUtil.java
Labels: enhancement

#24 fix #23
  src/main/java/su/svn/showcase/domain/LongEntity.java
  src/main/java/su/svn/showcase/domain/StringEntity.java
  src/main/java/su/svn/showcase/domain/UUIDEntity.java
Labels: bug

#25 Added entities: Role, UserRole, UserLogin, Tag, Record, NewsGroup, Ne…
  gradle/wrapper/gradle-wrapper.jar
  src/main/java/su/svn/showcase/domain/NewsEntry.java
  src/main/java/su/svn/showcase/domain/NewsGroup.java
  src/main/java/su/svn/showcase/domain/Record.java
  src/main/java/su/svn/showcase/domain/Role.java
  src/main/java/su/svn/showcase/domain/Tag.java
  src/main/java/su/svn/showcase/domain/UserLogin.java
  src/main/java/su/svn/showcase/domain/UserRole.java
Labels: bug

#28 Added unit tests for LongEntity, StringEntity and UUIDEntity.
  gradle/wrapper/gradle-wrapper.properties
  src/test/java/su/svn/showcase/domain/LongEntityTest.java
  src/test/java/su/svn/showcase/domain/StringEntityTest.java
  src/test/java/su/svn/showcase/domain/UUIDEntityTest.java
Labels: enhancement

#30 Added unit test for entities: Tag, Role, UserRole, UserLogin, Record,…
  gradle/wrapper/gradle-wrapper.properties
  src/test/java/su/svn/showcase/domain/NewsEntryTest.java
  src/test/java/su/svn/showcase/domain/NewsGroupTest.java
  src/test/java/su/svn/showcase/domain/RecordTest.java
  src/test/java/su/svn/showcase/domain/RoleTest.java
  src/test/java/su/svn/showcase/domain/StringEntityTest.java
  src/test/java/su/svn/showcase/domain/TagTest.java
  src/test/java/su/svn/showcase/domain/TestData.java
  src/test/java/su/svn/showcase/domain/UserLoginTest.java
  src/test/java/su/svn/showcase/domain/UserRoleTest.java
  src/test/java/su/svn/showcase/utils/StringUtilTest.java
  src/test/java/su/svn/utils/DummyUserTransaction.java
  src/test/java/su/svn/utils/SerializeUtil.java
  src/test/java/su/svn/utils/TestData.java
  src/test/java/su/svn/utils/ValidateUtil.java
Labels: enhancement

#33 Model 01
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/su/svn/showcase/domain/DBEntity.java
  src/main/java/su/svn/showcase/domain/LongEntity.java
  src/main/java/su/svn/showcase/domain/NewsEntry.java
  src/main/java/su/svn/showcase/domain/NewsGroup.java
  src/main/java/su/svn/showcase/domain/Record.java
  src/main/java/su/svn/showcase/domain/Role.java
  src/main/java/su/svn/showcase/domain/StringEntity.java
  src/main/java/su/svn/showcase/domain/Tag.java
  src/main/java/su/svn/showcase/domain/UUIDEntity.java
  src/main/java/su/svn/showcase/domain/UserLogin.java
  src/main/java/su/svn/showcase/domain/UserRole.java
  src/main/java/su/svn/showcase/utils/BigIntegerUtil.java
  src/main/java/su/svn/showcase/utils/LongUtil.java
  src/main/java/su/svn/showcase/utils/StringUtil.java
  src/test/java/su/svn/showcase/domain/LongEntityTest.java
  src/test/java/su/svn/showcase/domain/NewsEntryTest.java
  src/test/java/su/svn/showcase/domain/NewsGroupTest.java
  src/test/java/su/svn/showcase/domain/RecordTest.java
  src/test/java/su/svn/showcase/domain/RoleTest.java
  src/test/java/su/svn/showcase/domain/StringEntityTest.java
  src/test/java/su/svn/showcase/domain/TagTest.java
  src/test/java/su/svn/showcase/domain/TestData.java
  src/test/java/su/svn/showcase/domain/UUIDEntityTest.java
  src/test/java/su/svn/showcase/domain/UserLoginTest.java
  src/test/java/su/svn/showcase/domain/UserRoleTest.java
  src/test/java/su/svn/showcase/utils/StringUtilTest.java
  src/test/java/su/svn/utils/DummyUserTransaction.java
  src/test/java/su/svn/utils/SerializeUtil.java
  src/test/java/su/svn/utils/TestData.java
  src/test/java/su/svn/utils/ValidateUtil.java
Labels: bug, enhancement

#34 Model 01
  build.gradle
  gradle.properties
Labels: bug

#35 Dao 01
  .gitignore
  src/main/java/su/svn/shared/Constants.java
  src/main/java/su/svn/showcase/dao/Dao.java
  src/main/java/su/svn/showcase/dao/RoleDao.java
  src/main/java/su/svn/showcase/dao/TagDao.java
  src/main/java/su/svn/showcase/dao/UserRoleDao.java
  src/main/java/su/svn/showcase/dao/jpa/AbstractDaoJpa.java
  src/main/java/su/svn/showcase/dao/jpa/RoleDaoJpa.java
  src/main/java/su/svn/showcase/dao/jpa/TagDaoJpa.java
  src/main/java/su/svn/showcase/dao/jpa/UserRoleDaoJpa.java
  src/main/java/su/svn/showcase/domain/DBEntity.java
  src/main/java/su/svn/showcase/domain/LongEntity.java
  src/main/java/su/svn/showcase/domain/StringEntity.java
  src/main/java/su/svn/showcase/domain/UUIDEntity.java
  src/main/java/su/svn/showcase/utils/CollectionUtil.java
  src/main/resources/META-INF/persistence.xml
  src/test/java/su/svn/showcase/services/impl/RoleDaoJpaTest.java
  src/test/java/su/svn/showcase/services/impl/TagDaoJpaTest.java
  src/test/java/su/svn/showcase/services/impl/support/EntityManagerFactoryProducer.java
  src/test/java/su/svn/showcase/services/impl/support/EntityManagerProducer.java
  src/test/java/su/svn/showcase/services/impl/support/JtaEnvironment.java
  src/test/java/su/svn/showcase/services/impl/support/TestingTransactionServices.java
  src/test/java/su/svn/showcase/services/impl/support/TransactionalConnectionProvider.java
  src/test/resources/META-INF/services/org.jboss.weld.bootstrap.api.Service
  src/test/resources/META-INF/sql/create.sql
  src/test/resources/jndi.properties
Labels: enhancement

#43 Dao 03
  src/main/java/su/svn/showcase/dao/Dao.java
  src/main/java/su/svn/showcase/dao/NewsEntryDao.java
  src/main/java/su/svn/showcase/dao/NewsGroupDao.java
  src/main/java/su/svn/showcase/dao/RecordDao.java
  src/main/java/su/svn/showcase/dao/jpa/AbstractRecordDaoJpa.java
  src/main/java/su/svn/showcase/dao/jpa/RecordDaoJpa.java
  src/main/java/su/svn/showcase/dao/jpa/RoleDaoJpa.java
  src/main/java/su/svn/showcase/domain/Record.java
  src/main/java/su/svn/showcase/dto/NewsEntryFullDto.java
  src/main/java/su/svn/showcase/dto/RecordFullDto.java
  src/test/java/su/svn/showcase/domain/RecordTest.java
Labels: enhancement

#44 Dao 04
  src/main/java/su/svn/showcase/dao/Dao.java
  src/main/java/su/svn/showcase/dao/RecordDao.java
  src/main/java/su/svn/showcase/dao/jpa/AbstractDaoJpa.java
  src/main/java/su/svn/showcase/dao/jpa/AbstractRecordDaoJpa.java
  src/main/java/su/svn/showcase/dao/jpa/RecordDaoJpa.java
  src/main/java/su/svn/showcase/dao/jpa/RoleDaoJpa.java
  src/main/java/su/svn/showcase/dao/jpa/TagDaoJpa.java
  src/main/java/su/svn/showcase/dao/jpa/UserLoginDaoJpa.java
  src/main/java/su/svn/showcase/dao/jpa/UserRoleDaoJpa.java
  src/main/java/su/svn/showcase/domain/Role.java
  src/main/java/su/svn/showcase/exceptions/ErrorCase.java
  src/test/java/su/svn/showcase/services/impl/RecordDaoJpaTest.java
  src/test/java/su/svn/showcase/services/impl/RoleDaoJpaTest.java
  src/test/java/su/svn/showcase/services/impl/TagDaoJpaTest.java
  src/test/java/su/svn/showcase/services/impl/UserLoginDaoJpaTest.java
Labels: enhancement

#46 Refactoring TagDao, AbstractDaoJpa and AbstractRecordDaoJpa.
  src/main/java/su/svn/showcase/dao/TagDao.java
  src/main/java/su/svn/showcase/dao/jpa/AbstractDaoJpa.java
  src/main/java/su/svn/showcase/dao/jpa/AbstractRecordDaoJpa.java
  src/main/java/su/svn/showcase/dao/jpa/RecordDaoJpa.java
  src/main/java/su/svn/showcase/dao/jpa/TagDaoJpa.java
  src/main/java/su/svn/showcase/domain/Tag.java
Labels: enhancement

#50 Dao 07
  README.md
  src/test/java/su/svn/showcase/domain/NewsEntryTest.java
  src/test/java/su/svn/showcase/domain/RecordTest.java
  src/test/java/su/svn/showcase/domain/TestData.java
  src/test/java/su/svn/showcase/dto/NewsEntryBaseDtoTest.java
  src/test/java/su/svn/showcase/dto/RecordBaseDtoTest.java
  src/test/java/su/svn/showcase/dto/TagFullDtoTest.java
  src/test/java/su/svn/showcase/dto/TestData.java
  src/test/java/su/svn/showcase/services/impl/NewsEntryBaseCrudServiceImplTest.java
  src/test/java/su/svn/showcase/services/impl/NewsGroupBaseCrudServiceImplTest.java
  src/test/java/su/svn/showcase/services/impl/RecordDaoJpaTest.java
  src/test/java/su/svn/showcase/services/impl/RoleDaoJpaTest.java
  src/test/java/su/svn/showcase/services/impl/TagBaseCrudServiceImplTest.java
  src/test/java/su/svn/showcase/services/impl/TagDaoJpaTest.java
  src/test/java/su/svn/showcase/services/impl/UserLoginDaoJpaTest.java
Labels: enhancement

#51 Srv 02 user role service
  src/main/java/su/svn/showcase/dao/RoleDao.java
  src/main/java/su/svn/showcase/dao/UserRoleDao.java
  src/main/java/su/svn/showcase/dao/jpa/UserRoleDaoJpa.java
  src/main/java/su/svn/showcase/domain/UserRole.java
  src/main/java/su/svn/showcase/dto/NewsEntryFullDto.java
  src/main/java/su/svn/showcase/dto/RecordFullDto.java
  src/main/java/su/svn/showcase/dto/TagFullDto.java
  src/main/java/su/svn/showcase/dto/UserRoleFullDto.java
  src/main/java/su/svn/showcase/services/UserRoleFullCrudService.java
  src/main/java/su/svn/showcase/services/impl/UserRoleFullCrudServiceImpl.java
  src/test/java/su/svn/showcase/services/impl/RoleDaoJpaTest.java
  src/test/java/su/svn/showcase/services/impl/UserRoleFullCrudServiceImplTest.java
Labels: enhancement

#54 Srv 04 record full crud service
  src/main/java/su/svn/showcase/domain/NewsEntry.java
  src/main/java/su/svn/showcase/domain/Record.java
  src/main/java/su/svn/showcase/domain/Tag.java
  src/main/java/su/svn/showcase/domain/UserRole.java
  src/main/java/su/svn/showcase/dto/NewsEntryBaseDto.java
  src/main/java/su/svn/showcase/dto/NewsEntryDto.java
  src/main/java/su/svn/showcase/dto/NewsEntryFullDto.java
  src/main/java/su/svn/showcase/dto/RecordBaseDto.java
  src/main/java/su/svn/showcase/dto/RecordFullDto.java
  src/main/java/su/svn/showcase/dto/TagFullDto.java
  src/main/java/su/svn/showcase/dto/UserRoleDto.java
  src/main/java/su/svn/showcase/dto/UserRoleFullDto.java
  src/main/java/su/svn/showcase/services/NewsEntryBaseCrudService.java
  src/main/java/su/svn/showcase/services/NewsEntryFullCrudService.java
  src/main/java/su/svn/showcase/services/impl/AbstractUserTransactionService.java
  src/main/java/su/svn/showcase/services/impl/NewsEntryBaseCrudServiceImpl.java
  src/main/java/su/svn/showcase/services/impl/NewsEntryFullCrudServiceImpl.java
  src/main/java/su/svn/showcase/services/impl/RoleBaseCrudServiceImpl.java
  src/main/java/su/svn/showcase/services/impl/TagBaseCrudServiceImpl.java
  src/main/java/su/svn/showcase/services/impl/UserRoleFullCrudServiceImpl.java
  src/test/it/su/svn/it/DBIntegrationTest.java
  src/test/it/su/svn/it/IntegrationTestData.java
  src/test/java/su/svn/showcase/domain/TestData.java
  src/test/java/su/svn/showcase/domain/UserRoleTest.java
  src/test/java/su/svn/showcase/dto/NewsEntryBaseDtoTest.java
  src/test/java/su/svn/showcase/dto/TagFullDtoTest.java
  src/test/java/su/svn/showcase/dto/TestData.java
  src/test/java/su/svn/showcase/dto/UserRoleFullDtoTest.java
  src/test/java/su/svn/showcase/services/impl/NewsEntryFullCrudServiceImplTest.java
  src/test/java/su/svn/showcase/services/impl/TagBaseCrudServiceImplTest.java
  src/test/java/su/svn/showcase/services/impl/UserRoleFullCrudServiceImplTest.java
Labels: enhancement

#53 Work with integration tests.
  src/main/java/su/svn/showcase/domain/UserRole.java
  src/main/java/su/svn/showcase/dto/UserRoleDto.java
  src/main/java/su/svn/showcase/dto/UserRoleFullDto.java
  src/main/java/su/svn/showcase/services/impl/AbstractUserTransactionService.java
  src/main/java/su/svn/showcase/services/impl/RoleBaseCrudServiceImpl.java
  src/main/java/su/svn/showcase/services/impl/TagBaseCrudServiceImpl.java
  src/main/java/su/svn/showcase/services/impl/UserRoleFullCrudServiceImpl.java
  src/test/it/su/svn/it/DBIntegrationTest.java
  src/test/it/su/svn/it/IntegrationTestData.java
  src/test/java/su/svn/showcase/domain/TestData.java
  src/test/java/su/svn/showcase/domain/UserRoleTest.java
  src/test/java/su/svn/showcase/dto/TestData.java
  src/test/java/su/svn/showcase/dto/UserRoleFullDtoTest.java
Labels: enhancement

#57 Srv 04 record full crud service
  build.gradle
  src/main/java/su/svn/showcase/dao/jpa/NewsEntryDaoJpa.java
  src/main/java/su/svn/showcase/dao/jpa/NewsGroupDaoJpa.java
  src/main/java/su/svn/showcase/dao/jpa/RecordDaoJpa.java
  src/main/java/su/svn/showcase/dao/jpa/RoleDaoJpa.java
  src/main/java/su/svn/showcase/dao/jpa/TagDaoJpa.java
  src/main/java/su/svn/showcase/dao/jpa/UserLoginDaoJpa.java
  src/main/java/su/svn/showcase/dao/jpa/UserRoleDaoJpa.java
  src/main/java/su/svn/showcase/domain/NewsEntry.java
  src/main/java/su/svn/showcase/domain/Record.java
  src/main/java/su/svn/showcase/dto/RecordDto.java
  src/main/java/su/svn/showcase/dto/RecordFullDto.java
  src/main/java/su/svn/showcase/dto/RecordTypesEnum.java
  src/main/java/su/svn/showcase/services/NewsEntryTagsStorageService.java
  src/main/java/su/svn/showcase/services/RecordFullCrudService.java
  src/main/java/su/svn/showcase/services/impl/NewsEntryFullCrudServiceImpl.java
  src/main/java/su/svn/showcase/services/impl/NewsEntryTagsStorageServiceImpl.java
  src/main/java/su/svn/showcase/services/impl/RecordFullCrudServiceImpl.java
  src/main/java/su/svn/showcase/services/impl/UserRoleFullCrudServiceImpl.java
  src/test/java/su/svn/showcase/domain/TestData.java
  src/test/java/su/svn/showcase/dto/RecordBaseDtoTest.java
  src/test/java/su/svn/showcase/dto/RecordFullDtoTest.java
  src/test/java/su/svn/showcase/dto/TestData.java
  src/test/java/su/svn/showcase/services/impl/NewsEntryTagsStorageServiceImplTest.java
  src/test/java/su/svn/showcase/services/impl/RecordDaoJpaTest.java
  src/test/java/su/svn/showcase/services/impl/RecordFullCrudServiceImplTest.java
Labels: enhancement

#59 Build
  build.gradle
  src/main/java/su/svn/showcase/dao/jpa/NewsEntryDaoJpa.java
  src/main/java/su/svn/showcase/dao/jpa/NewsGroupDaoJpa.java
  src/main/java/su/svn/showcase/dao/jpa/RecordDaoJpa.java
  src/main/java/su/svn/showcase/dao/jpa/RoleDaoJpa.java
  src/main/java/su/svn/showcase/dao/jpa/TagDaoJpa.java
  src/main/java/su/svn/showcase/dao/jpa/UserLoginDaoJpa.java
  src/main/java/su/svn/showcase/dao/jpa/UserRoleDaoJpa.java
  src/main/java/su/svn/showcase/domain/NewsEntry.java
  src/main/java/su/svn/showcase/domain/Record.java
  src/main/java/su/svn/showcase/dto/NewsEntryDtoEnum.java
  src/main/java/su/svn/showcase/dto/NewsEntryFullDto.java
  src/main/java/su/svn/showcase/dto/RecordDto.java
  src/main/java/su/svn/showcase/dto/RecordFullDto.java
  src/main/java/su/svn/showcase/dto/RecordTypesEnum.java
  src/main/java/su/svn/showcase/dto/TagFullDto.java
  src/main/java/su/svn/showcase/services/NewsEntryTagsStorageService.java
  src/main/java/su/svn/showcase/services/RecordFullCrudService.java
  src/main/java/su/svn/showcase/services/impl/NewsEntryFullCrudServiceImpl.java
  src/main/java/su/svn/showcase/services/impl/NewsEntryTagsStorageServiceImpl.java
  src/main/java/su/svn/showcase/services/impl/RecordFullCrudServiceImpl.java
  src/main/java/su/svn/showcase/services/impl/UserRoleFullCrudServiceImpl.java
  src/main/java/su/svn/showcase/utils/CollectionUtil.java
  src/main/java/su/svn/showcase/utils/MapUtil.java
  src/test/it/su/svn/it/DBIntegrationTest.java
  src/test/it/su/svn/it/IntegrationTestData.java
  src/test/java/su/svn/showcase/domain/TestData.java
  src/test/java/su/svn/showcase/dto/RecordBaseDtoTest.java
  src/test/java/su/svn/showcase/dto/RecordFullDtoTest.java
  src/test/java/su/svn/showcase/dto/TagFullDtoTest.java
  src/test/java/su/svn/showcase/dto/TestData.java
  src/test/java/su/svn/showcase/services/impl/NewsEntryTagsStorageServiceImplTest.java
  src/test/java/su/svn/showcase/services/impl/RecordDaoJpaTest.java
  src/test/java/su/svn/showcase/services/impl/RecordFullCrudServiceImplTest.java
Labels: enhancement

#60 Refactoring NewsEntryDtoEnum and RecordTypesEnum.
  src/main/java/su/svn/showcase/dto/NewsEntryDtoEnum.java
  src/main/java/su/svn/showcase/dto/RecordTypesEnum.java
  src/main/java/su/svn/showcase/dto/UserLoginBaseDto.java
  src/main/java/su/svn/showcase/exceptions/ErrorCase.java
  src/main/java/su/svn/showcase/services/impl/NewsEntryFullCrudServiceImpl.java
  src/main/java/su/svn/showcase/services/impl/RecordFullCrudServiceImpl.java
  src/main/java/su/svn/showcase/utils/MapUtil.java
  src/main/resources/META-INF/persistence.xml
  src/test/it/su/svn/it/DBIntegrationTest.java
  src/test/it/su/svn/it/IntegrationTestData.java
  src/test/java/su/svn/showcase/dto/TagFullDtoTest.java
  src/test/java/su/svn/showcase/dto/TestData.java
  src/test/resources/META-INF/it-persistence.xml
Labels: enhancement

#61 Srv 05 record tags storage service
  src/main/java/su/svn/showcase/dto/NewsEntryDtoEnum.java
  src/main/java/su/svn/showcase/dto/RecordTypesEnum.java
  src/main/java/su/svn/showcase/dto/UserLoginBaseDto.java
  src/main/java/su/svn/showcase/exceptions/ErrorCase.java
  src/main/java/su/svn/showcase/services/NewsEntryTagsStorageService.java
  src/main/java/su/svn/showcase/services/RecordTagsStorageService.java
  src/main/java/su/svn/showcase/services/impl/NewsEntryFullCrudServiceImpl.java
  src/main/java/su/svn/showcase/services/impl/RecordFullCrudServiceImpl.java
  src/main/java/su/svn/showcase/services/impl/RecordTagsStorageServiceImpl.java
  src/main/java/su/svn/showcase/utils/MapUtil.java
  src/main/resources/META-INF/persistence.xml
  src/test/it/su/svn/it/DBIntegrationTest.java
  src/test/it/su/svn/it/IntegrationTestData.java
  src/test/java/su/svn/showcase/dto/TagFullDtoTest.java
  src/test/java/su/svn/showcase/dto/TestData.java
  src/test/java/su/svn/showcase/services/impl/RecordTagsStorageServiceImplTest.java
  src/test/resources/META-INF/it-persistence.xml
Labels: enhancement

#62 Added RecordsListModel and RecordsListView.
  build.gradle
  gradle.properties
  src/main/java/su/svn/showcase/primefaces/RecordsListModel.java
  src/main/java/su/svn/showcase/primefaces/RecordsListView.java
Labels: enhancement

#63 Added TagCloudView.
  src/main/java/su/svn/showcase/primefaces/TagCloudView.java
  src/test/it/su/svn/it/DBIntegrationTest.java
Labels: enhancement

#64 Added CalendarView.
  src/main/java/su/svn/showcase/primefaces/CalendarView.java
Labels: enhancement

#67 Refactoring.
  src/main/java/su/svn/showcase/dto/NewsEntryBaseDto.java
  src/main/java/su/svn/showcase/dto/NewsEntryDto.java
  src/main/java/su/svn/showcase/dto/NewsEntryFullDto.java
  src/main/java/su/svn/showcase/dto/RecordDto.java
  src/main/java/su/svn/showcase/dto/RecordFullDto.java
  src/main/java/su/svn/showcase/dto/UserLoginBaseDto.java
  src/main/java/su/svn/showcase/dto/UserOnlyLoginBaseDto.java
  src/main/java/su/svn/showcase/dto/UserRoleDto.java
  src/main/java/su/svn/showcase/dto/UserRoleFullDto.java
  src/main/java/su/svn/showcase/services/impl/NewsEntryFullCrudServiceImpl.java
  src/main/java/su/svn/showcase/services/impl/NewsGroupBaseCrudServiceImpl.java
  src/main/java/su/svn/showcase/services/impl/RecordFullCrudServiceImpl.java
  src/main/java/su/svn/showcase/services/impl/RecordTagsStorageServiceImpl.java
  src/main/java/su/svn/showcase/services/impl/RoleBaseCrudServiceImpl.java
  src/main/java/su/svn/showcase/services/impl/TagBaseCrudServiceImpl.java
  src/main/java/su/svn/showcase/services/impl/UserOnlyLoginRoServiceImpl.java
  src/main/java/su/svn/showcase/services/impl/UserRoleFullCrudServiceImpl.java
  src/test/it/su/svn/it/DBIntegrationTest.java
  src/test/it/su/svn/it/IntegrationTestData.java
  src/test/java/su/svn/showcase/dto/RecordFullDtoTest.java
  src/test/java/su/svn/showcase/dto/TestData.java
  src/test/java/su/svn/showcase/dto/UserRoleFullDtoTest.java
  src/test/java/su/svn/showcase/services/impl/NewsEntryFullCrudServiceImplTest.java
  src/test/java/su/svn/showcase/services/impl/RecordFullCrudServiceImplTest.java
Labels: enhancement

#70 fixed integration test.
  src/main/java/su/svn/showcase/domain/NewsEntry.java
  src/main/java/su/svn/showcase/dto/RecordFullDto.java
  src/main/java/su/svn/showcase/services/impl/NewsEntryFullCrudServiceImpl.java
  src/main/java/su/svn/showcase/services/impl/RecordFullCrudServiceImpl.java
  src/main/resources/META-INF/persistence.xml
  src/test/it/su/svn/it/DBIntegrationTest.java
  src/test/resources/META-INF/it-persistence.xml
Labels: bug

#72 Refactoring DTO's and Services.
  build.gradle
  gradle.properties
  src/main/java/su/svn/showcase/domain/NewsEntry.java
  src/main/java/su/svn/showcase/domain/NewsGroup.java
  src/main/java/su/svn/showcase/domain/Record.java
  src/main/java/su/svn/showcase/domain/Role.java
  src/main/java/su/svn/showcase/domain/Tag.java
  src/main/java/su/svn/showcase/domain/UserLogin.java
  src/main/java/su/svn/showcase/domain/UserRole.java
  src/main/java/su/svn/showcase/dto/Dto.java
  src/main/java/su/svn/showcase/dto/NewsEntryBaseDto.java
  src/main/java/su/svn/showcase/dto/NewsEntryDto.java
  src/main/java/su/svn/showcase/dto/NewsEntryDtoEnum.java
  src/main/java/su/svn/showcase/dto/NewsEntryFullDto.java
  src/main/java/su/svn/showcase/dto/NewsGroupBaseDto.java
  src/main/java/su/svn/showcase/dto/NewsGroupDto.java
  src/main/java/su/svn/showcase/dto/RecordBaseDto.java
  src/main/java/su/svn/showcase/dto/RecordDto.java
  src/main/java/su/svn/showcase/dto/RecordFullDto.java
  src/main/java/su/svn/showcase/dto/RecordTypesEnum.java
  src/main/java/su/svn/showcase/dto/RoleBaseDto.java
  src/main/java/su/svn/showcase/dto/RoleDto.java
  src/main/java/su/svn/showcase/dto/TagBaseDto.java
  src/main/java/su/svn/showcase/dto/TagDto.java
  src/main/java/su/svn/showcase/dto/TagFullDto.java
  src/main/java/su/svn/showcase/dto/UserLoginBaseDto.java
  src/main/java/su/svn/showcase/dto/UserLoginDto.java
  src/main/java/su/svn/showcase/dto/UserOnlyLoginBaseDto.java
  src/main/java/su/svn/showcase/dto/UserRoleDto.java
  src/main/java/su/svn/showcase/dto/UserRoleFullDto.java
  src/main/java/su/svn/showcase/interfaces/Updating.java
  src/main/java/su/svn/showcase/services/CrudService.java
  src/main/java/su/svn/showcase/services/RecordTagsStorageService.java
  src/main/java/su/svn/showcase/services/impl/AbstractUserTransactionService.java
  src/main/java/su/svn/showcase/services/impl/NewsEntryFullCrudServiceImpl.java
  src/main/java/su/svn/showcase/services/impl/NewsGroupBaseCrudServiceImpl.java
  src/main/java/su/svn/showcase/services/impl/RecordFullCrudServiceImpl.java
  src/main/java/su/svn/showcase/services/impl/RecordTagsStorageServiceImpl.java
  src/main/java/su/svn/showcase/services/impl/RoleBaseCrudServiceImpl.java
  src/main/java/su/svn/showcase/services/impl/TagBaseCrudServiceImpl.java
  src/main/java/su/svn/showcase/services/impl/UserOnlyLoginRoServiceImpl.java
  src/main/java/su/svn/showcase/services/impl/UserRoleFullCrudServiceImpl.java
  src/test/java/su/svn/showcase/dto/RecordBaseDtoTest.java
  src/test/java/su/svn/showcase/dto/TestData.java
  src/test/java/su/svn/showcase/services/impl/NewsEntryFullCrudServiceImplTest.java
  src/test/java/su/svn/showcase/services/impl/RecordFullCrudServiceImplTest.java
Labels: enhancement
